[alias]
rel = "build --release"
inst = "install --path .
clip = "clippy --release"

[build]
target = "x86_64-unknown-linux-musl"

[install]
target = "x86_64-unknown-linux-musl"

[publish]
pub = "publish --target=x86_64-unknown-linux-musl"

[clippy]
target = "x86_64-unknown-linux-musl"
